version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./infra/app/Dockerfile
    container_name: table-sample-vue
    command: npm run dev
    ports:
      - 3000:5173
    volumes:
      - ./front:/app
    stdin_open: true
    tty: true
  
  web:
    container_name: vue-backend
    build:
      context: ./
      dockerfile: ./infra/web/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./server:/app
    tty: true
    environment:
      - TZ=Asia/Tokyo
  
  db:
    container_name: vue_table_db
    build:
      context: ./
      dockerfile: ./infra/db/Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data: