version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./infra/app/Dockerfile
    container_name: table-sample-vue
    command: npm run dev
    ports:
      - 3000:5173
    volumes:
      - ./front:/app
    stdin_open: true
    tty: true